# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95444ea36f7f14b840bb9ae69f15ea867eeb94a05f99a16358a151a75acff81c4a24ea125dbbc59f51961242066167a0d9971bb5609b3c9dd7a36ffa7b894bfe

test:
  secret_key_base: 5db359bb964efe1940278b14a4c0637ce6edb107824eccabbf88a8ea8c4fb0f095d0f0a87f706853da7218245327265efac3cb6cccc86770ada47b5bc396692d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
